### ISSUE TITLE
How do you run the imessages-data-extract-and-prep.ipynb file?

### ISSUE THREAD

**Issue by cryo-kronos** [yortos/imessage-analysis#3]
I'm a python noob. I tried converting the ipynb file to a python script and running it but it failed with a "No module named 'matplotlib'" error despite matplotlib being installed.

I then finally figured out how to install Jupyter and run the file but it still fails with  "ModuleNotFoundError: No module named 'matplotlib'".

So, I don't know if I'm doing something wrong (most likely) or there's something wrong with the script.

Any ideas how to fix it or plans to release a python script version for easy execution?

**Comment by zackse** [comment]
Note: it may be easiest to work in a virtualenv/pyenv. (For Python 2, `pip install virtualenv && virtualenv imessages-venv && source imessage-venv/bin/activate`)

If you `pip install jupyter pandas matplotlib`, you should get all of the necessary dependencies installed. Then navigate to the folder where you cloned the repo, and run `jupyter-notebook`. This should open your default web browser to the service now running on your machine. If it doesn't, examine the output from the command -- it should contain the URL you can paste into your browser manually.

In the browser, you should see a list of files in the current directory. Click on the `.pynb` file and it should open in a new tab.

You can execute the code in each block by moving the cursor into it, then pressing Ctrl-Enter (or clicking the Run button) to execute the code it contains. If there is any output, it will appear below the code block.

**Comment by what2be** [comment]
Im getting this error at line 2808 
KeyError                                  Traceback (most recent call last)
<ipython-input-9-94efdcffb7e2> in <module>
      1 # merge the messages with the handles
----> 2 merge_level_1 = pd.merge(messages[['text', 'handle_id', 'date','message_date' ,'timestamp', 'month','year','is_sent', 'message_id']],  handles[['handle_id', 'phone_number']], on ='handle_id', how='left')
      3 
      4 # and then that table with the chats
      5 df_messages = pd.merge(merge_level_1, chat_message_joins[['chat_id', 'message_id']], on = 'message_id', how='left')

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2804             if is_iterator(key):
   2805                 key = list(key)
-> 2806             indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
   2807 
   2808         # take() does not accept boolean indexers

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1550 
   1551         self._validate_read_indexer(
